### ISSUE TITLE
ExampleOptionList.py does not run

### ISSUE THREAD

**Issue by oliveratutexas** [npcole/npyscreen#28]
I downloaded npyscreen and tried to run this file but I get an error. I rand several other examples, but this is the only one that seems to give me problems: 

Traceback (most recent call last):
  File "EXAMPLE-OptionList.py", line 43, in <module>
    App.run()   
  File "filepath/npyscreen-4.9.1/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "filepath/npyscreen-4.9.1/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "filepath/npyscreen-4.9.1/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "filepath/npyscreen-4.9.1/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "EXAMPLE-OptionList.py", line 27, in main
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

**Comment by npcole** [comment]
Thanks. I'll have a look later.

**Comment by npcole** [comment]
Looks like I've used a Python3 only exception. Should be IOError on
Python2. I'll fix when I'm back at my desk later.

**Comment by gaining** [comment]
I see this issue is from 2015, you still haven't fixed it. Is this project dead??

**Comment by gaining** [comment]
These lines were the culprit of your broken code. I removed them for now and now it works.  
```
 try:
            Options.reload_from_file('/tmp/test')
        except IOError:
            pass
```

**Comment by npcole** [comment]
It's not dead. It's just been sleeping a bit.  There are quite a few issues
to push out in a fix, and I'll try to do that this week.
