### ISSUE TITLE
warandpeace.py refers to non-existent file

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [npcole/npyscreen#30]
```
~/Developer/npyscreen on master ⌚ 14:09:54
$ python example-war-and-peace.py
Traceback (most recent call last):
  File "example-war-and-peace.py", line 22, in <module>
    App.run()
  File "/Users/CVoncsefalvay/Developer/npyscreen/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/Users/CVoncsefalvay/Developer/npyscreen/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/Users/CVoncsefalvay/Developer/npyscreen/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "/Users/CVoncsefalvay/Developer/npyscreen/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "example-war-and-peace.py", line 12, in main
    with open("/Users/nicholas/Downloads/pg2600.txt", 'r') as war_and_peace:
IOError: [Errno 2] No such file or directory: '/Users/nicholas/Downloads/pg2600.txt'
```

Include this file or get rid of example?

**Comment by npcole** [comment]
Good point!

N
