### ISSUE TITLE
EXAMPLE-OptionList.py doesn't work

### ISSUE THREAD

**Issue by gaining** [npcole/npyscreen#46]
I get these runtime errors when trying to run it:
Traceback (most recent call last):
  File "EXAMPLE-OptionList.py", line 43, in <module>
    App.run()   
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "EXAMPLE-OptionList.py", line 27, in main
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

I replace FileNotFoundError exeption with IOError since filenotfound doesn't exist but yeah the other ones are something else.

**Comment by gaining** [comment]
fixed it by removing

`   try:
            Options.reload_from_file('/tmp/test')
     except IOError:
            pass
`
